# URL de conexão com o banco local ou valor vindo de variáveis de ambiente
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ConectaMesa}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:15031811}

# Configuração JPA para desenvolvimento; use migrations em produção
spring.jpa.hibernate.ddl-auto=update

# Imprime SQL apenas em desenvolvimento
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true